export const GOOGLE_SHEET_ID = '1XmFc32Fvd7UiBTRxvsgwGnR_1c69f7J3UlDgvTlkj8M';
export const GOOGLE_SPREADSHEETS_RAW_DATA_KEY = '_rawData';



export const Indices = {
	PRACTITIONER: {
		ID: 0,
		LICENSE_NUMBER: 1,
		MD_USE: 2,
		FAMILY_NAME: 3,
		GIVEN_NAME: 4,
		PREFIX: 5,
		SUFFIX: 6,
	},
	PATIENT:{
		ID: 0,
		ETHNICITY_CODE: 1,
		ETHNICITY_DISPLAY: 2,
		FAMILY_ID: 3,
		IS_PROBAND: 4,
		BLOOD_RELATIONSHIP_CODE: 5,
		IDENTIFIER_TYPE_VALUE_MR: 6,
		IDENTIFIER_TYPE_VALUE_JHN: 7,
		ACTIVE: 8,
		NAME_USE: 9,
		FAMILY_NAME: 10,
		GIVEN_NAME: 11,
		BIRTHDATE: 12,
		GENDER: 13,
		GENERAL_PRACTITIONER: 14,
		MANAGING_ORGANISATION: 15,
	}
}
